define(["DQX/Utils", "DQX/Controls", "DQX/Msg", "DQX/Popup"],
    function (DQX, Controls, Msg, Popup) {
        var MetaData = {};


        MetaData.serverUrl="http://localhost:8000/app01";
        //MetaData.serverUrl="http://panoptes.cggh.org/sandbox/dqx_server_test/app";

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Data source tables
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        MetaData.database = 'pf21';
        //MetaData.database = 'pfpopgen';
        MetaData.tableSNPInfo = 'pfsnprel21'; //SNP information (including population frequencies)
        MetaData.tableAnnotation = 'pfannotrel21'; //Genome annotation
        MetaData.genotypeDataSource = 'SNP-PfPopGen2.1/public';
        MetaData.tableCountries = 'countries';
        MetaData.tableSiteInfo = 'location'; //Information about sampling sites
        MetaData.tableStudy = 'study'; //Information about studies
        MetaData.tableSampleContextInfo = 'sample_context'; //Information about study contexts
        MetaData.tableSample = 'sample'; //Information about studies
        MetaData.tableSampleClassification = 'sample_classification';
        MetaData.tableSampleClassificationType = 'sample_classification_type';
        MetaData.tableSampleClassificationContextCount = 'sample_classification_context_count'; //Contains # of samples for each sampleclassification x samplecontext combination
        MetaData.tableMarkerGeneInfo = 'pf21geneinfo'; //Information about genes containing known resistance loci
        MetaData.tableMarkerLociInfo = 'pf21loci'; //Information about known resistance loci
        MetaData.tableMarkerLociSnpInfo = 'pf21locisnps'; //Information about known snps in resistance loci
        MetaData.tableMarkerLociVariantInfo = 'pf21locivariants'; //Information about variants of known resistance loci
        MetaData.tableMarkerLociFrequencies = 'pf21locusfreqs'; //The variant frequencies of the loci

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Define the metadata that is generated by the client (NOTE: some of this stuff should move to the server)
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////


        //////// Information about the chromosomes
        MetaData.chromosomes = [
            { idx: 1, id: 'MAL1', len: 0.7 },
            { idx: 2, id: 'MAL2', len: 1 },
            { idx: 3, id: 'MAL3', len: 1.2 },
            { idx: 4, id: 'MAL4', len: 2 },
            { idx: 5, id: 'MAL5', len: 2 },
            { idx: 6, id: 'MAL6', len: 2 },
            { idx: 7, id: 'MAL7', len: 2 },
            { idx: 8, id: 'MAL8', len: 2 },
            { idx: 9, id: 'MAL9', len: 2 },
            { idx: 10, id: 'MAL10', len: 2 },
            { idx: 11, id: 'MAL11', len: 4 },
            { idx: 12, id: 'MAL12', len: 4 },
            { idx: 13, id: 'MAL13', len: 4 },
            { idx: 14, id: 'MAL14', len: 4 }
        ];
        $.each(MetaData.chromosomes, function (idx, chr) { chr.name = chr.id; });
        MetaData.chrom_map = DQX.attrMap(MetaData.chromosomes, 'id');

        MetaData.populations=[
            { freqid:'NRAF_WAF', name:"West Africa", color:DQX.Color(1,0,0) },
            { freqid:'NRAF_EAF', name:"East Africa", color:DQX.Color(0,0,1) }
            //{ freqid:'NRAF_SEA', name:"South-east Asia", color:DQX.Color(0,0.7,0.5) }
        ];

        MetaData.summaryFolder='Tracks-PfPopGen2.1';//Location of the summary data, relative to the base path defined by DQXServer
        MetaData.summaryConfig='Summ01';//ID of the summary configuration used


        //List of all the summary profiles displayed in the app
        MetaData.summaryProfiles=[
            { id:'GC300', name:"%GC" },
            { id:'Uniqueness', name:"Uniqueness" }
        ];


        return MetaData;
    });